### ISSUE TITLE
Is connecting to SQL 2005 supported?

### ISSUE THREAD

**Issue by RickMura** [burningalchemist/sql_exporter#110]
I tried to connect to an instance I have here but I got the following error message.
I0609 13:48:51.560255 6 promhttp.go:38] Error gathering metrics: [from Gatherer #1] Login error: EOF
I0609 13:49:21.536107 6 promhttp.go:38] Error gathering metrics: [from Gatherer #1] Login error: EOF
I0609 13:49:51.527936 6 promhttp.go:38] Error gathering metrics: [from Gatherer #1] Login error: read tcp prometheusIP:Port->SQLIP:Port: read: connection reset by peer

The same configuration works just fine in SQL 2012.

**Comment by burningalchemist** [comment]
Hi @RickMura! The error comes from the mssql driver.

I've taken a look at the repo and found your case. Take a look here: https://github.com/denisenkom/go-mssqldb/issues/399

So answering your question, it's supported but might require some additional configuration.

Let me know if this helped.

Cheers,
Sergei

**Comment by burningalchemist** [comment]
@RickMura did it help in the end? :)
