### ISSUE TITLE
Backward compatible

### ISSUE THREAD

**Issue by dtoxin7** [burningalchemist/sql_exporter#12]
Hi! Is this fork backward compatible with the binary from original repo? Do the commands and functions that work in the original version also work in this one?

**Comment by burningalchemist** [comment]
@dtoxin7 Yes it is. 👍 There are no breaking changes in commands and functions.
If there's a new approach, implementation or a breaking change, it will be a part of a new project.

The goal of this fork is:
- maintain the existing approach by original author;
- improve quality / fix issues;
- keep up with up-to-date dependencies, good security practices;
- add some features if necessary;
- support users of the sql exporter.

**Comment by dtoxin7** [comment]
Thanks for your answer!
