### ISSUE TITLE
from Gatherer #1] pq: SSL is not enabled on the server

### ISSUE THREAD

**Issue by prashantnitt07** [burningalchemist/sql_exporter#122]
getting error from sql_exporter agent

No metrics gathered, [from Gatherer #1] pq: SSL is not enabled on the server

**Comment by prashantnitt07** [comment]
I0802 17:54:36.378701 2655919 promhttp.go:39] Error gathering metrics: [from Gatherer #1] pq: SSL is not enabled on the server
I0802 17:56:11.561959 2655919 promhttp.go:39] Error gathering metrics: [from Gatherer #1] pq: SSL is not enabled on the server
I0802 17:59:24.927661 2655919 promhttp.go:39] Error gathering metrics: [from Gatherer #1] pq: SSL is not enabled on the server
^C

**Comment by burningalchemist** [comment]
Hi @prashantnitt07, not a bug. The message comes from the driver and states that the PostgreSQL doesn't have SSL connection enabled.

You can add `?sslmode=disable` parameter to your connection string, this should solve the issue.

**Comment by prashantnitt07** [comment]
thanks , working fine after add in DSN

**Comment by prashantnitt07** [comment]
postgres://username:password@host:5432/database?sslmode=disable
