### ISSUE TITLE
basic authentication is not implemented

### ISSUE THREAD

**Issue by aefde** [burningalchemist/sql_exporter#139]
Hi 

I downloaded latest version for windows and installed.

But I can't see option "--web.config.file" for basic authentication indicated in document.

######################################################
flag provided but not defined: -web.config.file
Usage of C:\Program Files\sql_exporter\sql_exporter.exe:
  -add_dir_header
        If true, adds the file directory to the header of the log messages
  -alsologtostderr
        log to standard error as well as files (default true)
  -config.data-source-name string
        Data source name to override the value in the configuration file with.
  -config.enable-ping
        Enable ping for targets (default true)
  -config.file string
        SQL Exporter configuration filename (default "sql_exporter.yml")
  -log_backtrace_at value
        when logging hits line file:N, emit a stack trace
  -log_dir string
        If non-empty, write log files in this directory
  -log_file string
        If non-empty, use this log file
  -log_file_max_size uint
        Defines the maximum size a log file can grow to. Unit is megabytes. If t
he value is 0, the maximum file size is unlimited. (default 1800)
  -logtostderr
        log to standard error instead of files (default true)
  -one_output
        If true, only write logs to their native severity level (vs also writing
 to each lower severity level)
  -skip_headers
        If true, avoid header prefixes in the log messages
  -skip_log_headers
        If true, avoid headers when opening log files
  -stderrthreshold value
        logs at or above this threshold go to stderr (default 2)
  -v value
        number for the log level verbosity
  -version
        Print version information
  -vmodule value
        comma-separated list of pattern=N settings for file-filtered logging
  -web.enable-reload
        Enable reload collector data handler
  -web.listen-address string
        Address to listen on for web interface and telemetry (default ":9399")
  -web.metrics-path string
        Path under which to expose metrics (default "/metrics")
#######################################################

It is possible include this option ?

Thanks for any.
Regards

**Comment by burningalchemist** [comment]
Hey @aefde, it's implemented but not released yet. You can clone the `master` branch and build it yourself in the meantime (check the docs).

Let me know if you need help.

**Comment by aefde** [comment]
Ok, thanks.
