### ISSUE TITLE
dashboard

### ISSUE THREAD

**Issue by myabce** [burningalchemist/sql_exporter#144]
has a dashboard for this sql_exporter？

**Comment by burningalchemist** [comment]
Hi @myabce,

do you mean Grafana dashboard? There is no dashboard as the metrics are arbitrary.

**Comment by mohammadfalahat** [comment]
is there a ready to use grafana dashboard for this exporter?

**Comment by burningalchemist** [comment]
@mohammadfalahat you can try this one as an example - https://github.com/burningalchemist/sql_exporter/tree/master/examples/azure-sql-mi

But the thing - there is no default dashboard as sql_exporter expects users to define their own queries for the database of their choice. Users are welcome to contribute their examples if needed, I'm happy to accept such PRs.
