### ISSUE TITLE
Collected Before Error

### ISSUE THREAD

**Issue by BenHesketh21** [burningalchemist/sql_exporter#145]
**Describe the bug**
At the moment any metrics the exporter collects create an error: "was collected before with the same name and label values"

**To Reproduce**
1. Create a metric that wont change value on the next run

**Expected behavior**
I wouldn't have thought this was an error, this is surely a common occurrence?

**Comment by burningalchemist** [comment]
Hi @BenHesketh21,

I need more details as the steps you described won't help with reproducing the case.

Could you please share the following details:
- db driver
- the configuration file

My current assumption is that something is wrong in your configuration file.

**Comment by burningalchemist** [comment]
Let me know if you need any additional help, I'll close the issue so far.
