### ISSUE TITLE
Using your repo as the base for our Vertica centric exporter repo

### ISSUE THREAD

**Issue by verticacrossman** [burningalchemist/sql_exporter#147]
Hi,
Sorry, couldn't find any other way to reach out. I work for Vertica in the Partner Engineering/Integrations group. We recently pulled your repo to use as a starting point for a Vertica centric open source exporter, as last year you had added Vertica support for connectivity. We are basically stripping out the other databases, adding Vertica centric enhancements including Vertica metric file examples, different logging mechanism, optimized docker builds, pull request test suites, etc. Because these were breaking changes we opted to not branch your code but to download the zip and create our own project. We wanted to let you know our intentions prior to release (currently hoping for early Oct). We plan on adding some kudos to you in our Readme.md noting it your repo was the solid base which we used as a jump off point. If any interest in discussing please let me know how best to reach  you. 
Thanks and regards,
Stephen Crossman
Vertica, a Microfocus business unit.

**Comment by burningalchemist** [comment]
@verticacrossman

Hey Stephen, thanks for letting me now. :+1:
It'd be great to know about the breaking changes you identified.

Besides that, I guess it's a good idea. I'd then go and disable vertica driver from the basic installation, and instead point at your vendor-maintained exporter.

My email for the contacts (just in case): `oss[at]szyubin[dot]me`

Kind regards,
Sergei

**Comment by hhromic** [comment]
> Besides that, I guess it's a good idea. I'd then go and disable vertica driver from the basic installation, and instead point at your vendor-maintained exporter.

Hi @burningalchemist , sorry to comment on a closed issue.
Our team works with Vertica since a long time and we decided to give the "official" Vertica exporter a try. Unfortunately, it is not very well implemented, doesn't seem very well maintained and has some important issues currently. Later we realised that it is actually a fork of your SQL exporter, which I just tried and everything is working really well and as expected.

For this reason, please reconsider on removing the Vertica driver from your exporter and instead on keeping it 🙏.
Kudos and thanks for your excellent SQL exporter!

**Comment by burningalchemist** [comment]
Hi @hhromic, gotcha! Thanks a lot for your feedback! We keep it in-tree then. 🙂👍

**Comment by verticacrossman** [comment]
Hi @hhromic,

I was a bit surprised at your comments regarding our Vertica Prometheus Exporter. We took the basic burningalchemist exporter, made it Vertica only, and added a lot of enhancements and documentaiton. We've done 3 releases since October's release. We've only had one issue reported that ended up being a missing Vertica role on the customer's end. Please provide details on our Exporter's Github page (https://github.com/vertica/Vertica-Prometheus-Exporter) and let us know what issues you faced and why you feel it's not well implemented or maintained. We'd appreciate some feedback so we can either correct or clarify your various issues and concerns. Regards,

**Comment by hhromic** [comment]
Hi @verticacrossman,
First of all, apologogies for the rather harsh comment I made regarding the Vertica fork. It was a bit late yesterday and was quite frustrated by that fork not working as needed. On the other hand, the fork here worked exactly like we need and thus I mostly wanted the devleoper to not drop Vertica support in the official binaries.

The extra documentation in the Vertica fork seems good and is appreciated but is not clear what are the enhancements you mention in comparison to the original fork here. Perhaps it would be a good idea to clarify that in your repository as we didn't find a reason to prefer the Vertica fork over the SQL exporter version.

We will continue using the SQL exporter at the time being, but when we have a chance we will give the Vertica fork another try so we can report our feedback to your repository as well. 👍

**Comment by verticacrossman** [comment]
@hhromic,

No worries. With the details you supplied we consider it constructive criticism. Will follow up with you on the issues you logged. We apprecaite you taking the time to provide feedback. Regards,
