### ISSUE TITLE
Re-load on change of the configuration file or the collector files

### ISSUE THREAD

**Issue by WalBeh** [burningalchemist/sql_exporter#15]
It would come quite handy if a change of the configuration file or the collector files is detected and a _reload_ is triggered. Especially handy while running it on k8s and providing the configuration as a kubernetes configmap.

I hope this makes sense.

thanks for the great work and best greetings,
Walter

**Comment by burningalchemist** [comment]
Hi Walter, the requested change was made for collector files, please take a look. It's a simple implementation, but hopefully will serve your needs. With the `/reload` handler enabled (via `-web.enable-reload` flag) we can reload the queries running against the configured connection. The watch function to detect changes in configMap has to be run externally at the moment (as a sidecar), e.g. with one of the following solutions:
- https://github.com/weaveworks/Watch
- https://github.com/watchexec/watchexec
