### ISSUE TITLE
Spaces in %SQL_EXPORTER_PATH% prevents service startup

### ISSUE THREAD

**Issue by DerfOh** [burningalchemist/sql_exporter#155]
**Describe the bug**
The exporter service fails to start when the path includes a space

**To Reproduce**
1. Download necessary files to C:\Program Files\sql-exporter
2. Use examples in README.md to create service entry in windows
3. Open services dialogue, click on created service and run
4. See error: windows could not start the SqlExporterSvc service on local computer error 1067

**Expected behavior**
Service to start as expected 

**Configuration**
Default configs using documentation example (entered in db info of course) 

**Additional context**
This only seems to happen for me when I'm trying to place the service in a path with spaces in it's name. If I put the extracted release folder on the root of C:\ everything behaves as expected.

**Comment by burningalchemist** [comment]
Hi @DerfOh, it's not a part of `sql_exporter` implementation on how to handle paths in Windows.

The standard way to ensure Windows treats a file path properly is to enclose it in double quotation mark (") characters. Give it a shot. :+1:

**Comment by DerfOh** [comment]
To clarify you're saying if I have spaces to try wrapping the example command with a second set of quotes as such? 
```
New-Service -name "SqlExporterSvc" `
-BinaryPathName ""%SQL_EXPORTER_PATH%\sql_exporter.exe -config.file %SQL_EXPORTER_PATH%\sql_exporter.yml"" `
-StartupType Automatic `
-DisplayName "Prometheus SQL Exporter"`
```

**Comment by DerfOh** [comment]
Understand now what you meant by it being a windows issue. Fixed it by using a single quote and surrounding paths with doubles as follows:

New-Service -name "SqlExporterSvc" `
-BinaryPathName '"C:\Program Files\sql-exporter\sql_exporter.exe" -config.file "C:\Program Files\sql-exporter\sql_exporter.yml"' `
-StartupType Automatic `
-DisplayName "Prometheus SQL Exporter"`

**Comment by burningalchemist** [comment]
I had to find my old Windows laptop to try it out. But yeah, exactly this. 👍

**Comment by DerfOh** [comment]
Thanks! I imagine there's a better way to do it, not sure if single quotes will break variable expansion, but this works for me for now.
