### ISSUE TITLE
Environment variables to override connection string and collectors list

### ISSUE THREAD

**Issue by lukos** [burningalchemist/sql_exporter#161]
As a containerised app, the current implementation doesn't seem to support using either a secret and/or an environment variable to set the secret parts of the connection string and/or to adjust the list of collectors. These are both in the root config file, which although it can be treated as an entire secret, means that whoever needs to configure the e.g. scrape timeout offset, also would need access to the secrets.

A solution I have implemented locally allows an optional environment variable that can set the DSN or the collectors list (the second I am not sure if it is as useful). This code is very simple:

```go
func (t *TargetConfig) UnmarshalYAML(unmarshal func(interface{}) error) error {
	type plain TargetConfig
	if err := unmarshal((*plain)(t)); err != nil {
		return err
	}

        // My new block below
	// Look for env variable to overwrite
	if val, ok := os.LookupEnv("SQLEXPORTER_DSN"); ok {
		t.DSN = Secret(val)
	}

	// Check required fields
	if t.DSN == "" {
		return fmt.Errorf("missing data_source_name for target %+v", t)
	}
        // etc.
```

I am not sure if there are other ways to achieve the same thing but this allows my deployment tool to inject an environment variable with the correct DSN passwords in it per-environment.

If you are happy with this, I am happy to create a PR but as a Go noob, I don't know if I have missed any edge cases (like Nil errors)

**Comment by burningalchemist** [comment]
Closed due to inactivity.

**Comment by matt-baker-agd-systems** [comment]
Should `SQLEXPORTER_TARGET_DSN` be in the README.md if still valid?

**Comment by burningalchemist** [comment]
Hi @matt-baker-agd-systems, yes it’s still valid. I’ll update the readme to list the available environment variables.  I plan to create proper a documentation source as the information has accumulated over the years.

My capacity is currently limited but we can make small improvements gradually. 👍 

UPD: The readme has been updated, thank you for the suggestion. 😃👍
