### ISSUE TITLE
No metrics gathered, [from Gatherer #1] context deadline exceeded

### ISSUE THREAD

**Issue by jdstone** [burningalchemist/sql_exporter#179]
What does `No metrics gathered, [from Gatherer #1] context deadline exceeded` mean?  I'm receiving that when viewing the `/metrics` HTML page in a browser.

**Comment by burningalchemist** [comment]
Your connection to the remote endpoint wasn't established properly, so no metrics were gathered. Check your connection string (username, password, hostname, port, database, etc.)

**Comment by jdstone** [comment]
Ah, that's helpful.  Thank you!

**Comment by burningalchemist** [comment]
@jdstone With Azure MSSQL it might be tricky, since I can't really reproduce and test all the features. But happy to help as much as I can. 🙂
