### ISSUE TITLE
Question about sql_exporter reading the config file

### ISSUE THREAD

**Issue by jdstone** [burningalchemist/sql_exporter#181]
Hello,

I'm running sql_exporter in a Kubernetes container and I've got a solution in place to read in the database user and password from an Azure Key Vault by way of mounting the secret as a volume mount (ex. `/mnt/secret/DB-PASSWORD`) and then dynamically modify the Data Source Name in the configuration file (`sql_exporter.yml`) with the credentials of the database.  This works well when the pod (container) first starts up, but when the password is rotated (updated), and the configuration file gets updated while the container is running, are there any mechanisms in place in sql_exporter to check the config file for changes?  For example, if sql_exporter can't connect to the database, so it reads the config file again to check for changes?  Or does the application only read the configuration file on startup?  I assume it's the latter.

Thank you in advance for your help.

**Comment by burningalchemist** [comment]
Hi @jdstone,

Yeah, you're right. Currently the config file is only read once on startup. What I might suggest as an option is [Reloader](https://github.com/stakater/Reloader). It's an additional component, but it solves exactly this type of problems. Please have a look.

At the moment sql_exporter has a straightforward workflow, so introducing a config file watcher requires revisiting the codebase (we need to watch for changes continuously, detect them, drop previously created objects like Exporter->Target->Collector->Query, and recreate them again with a new config, then reconnect).

I'll think about it, but for the time being to unblock you I'd recommend looking at Reloader or any similar solution. Password change is an operational event, so I'd rather make it noticeable for the applications as well.

P.S. I'm sorry, I was away from my computer for some time, so I didn't answer your previous question (regarding `jobs`). Is it still relevant? 

Kind regards,
Sergei

**Comment by jdstone** [comment]
Hey @burningalchemist,

Oooh, Reloader looks like exactly what I want.  Though I'm trying the Azure Active Directory authentication approach, as I've asked about in my other open issue, #169.  So hopefully I can get that working.

Yeah, it makes sense that you'd have to revisit the codebase and workflow if you introduce a config file watcher.  There is probably no point (and probably doesn't make sense) in pursuing this since I'm sure this project has more important priorities.  And it really isn't sql_exporter's job to watch for config file changes -- not the purpose of this application.

No worries about being away; you're allowed to have a life outside this software, haha.  :)
I assume you're referring to my questions here?  Yes, those questions are still relevant.  It'd be much appreciated if you could answer them to the best of your ability.
https://github.com/burningalchemist/sql_exporter/issues/37#issuecomment-1374234916

**Comment by burningalchemist** [comment]
@jdstone cool, will do. I'll close this issue for the time being. But I'll take your feedback as a feature request. 👍
