### ISSUE TITLE
Add support for globbing to `resolveCollectorRefs()`

### ISSUE THREAD

**Issue by hhromic** [burningalchemist/sql_exporter#184]
**Is your feature request related to a problem? Please describe.**

Currently, the `target` configuration requires a list of collector names in `collectors`.
The names must be previously defined via `collector_files` or inline in the top-level `collectors` config.

These collector names are resolved from defined collectors using `resolveCollectorRefs()`:
https://github.com/burningalchemist/sql_exporter/blob/2ff59aa752005d027182d6bc3204774783093de3/config/config.go#L546-L558

However, the current implementation is limited only to _full collector names_ to be resolved. When you leverage the handy `collector_files` config, which supports globbing, it is not sufficient to just add new files that match the globbing pattern. Any new collector names must be added also to `target.collectors`. Therefore, despite using globbing patterns on the collector file names, one is still forced to keep `target.collectors` updated manually.

**Describe the solution you'd like**

A nice enhancement to the `target.collectors` configuration could be to add support for globbing patterns for the collector names. In this way, it would be possible to easily tell the exporter to "use all collectors with names using these patterns". For example:
```yaml
global: {}
target:
  data_source_name: driver://host/dbname
  collectors: ['users_*', 'prices_*', 'stocks']
collector_files: ['*.collector.yaml']
```

For example, a main configuration like this:
```yaml
global: {}
target:
  data_source_name: driver://host/dbname
  collectors: ['*']
collector_files: ['*.collector.yaml']
```
Would simply use all available collectors found via `collector_files`, without altering the same main config file when new collector YAML files are added.

**Describe alternatives you've considered**

At the moment, we are using a wrapper shell script that scans all the available `*.collector.yaml` files and extracts the `collector_name` values from them. Then, we manually generate an array of these names to provide in `target.collectors` in a generated main config file before starting the SQL exporter.

EDIT: Here is the POSIX sh snippet that collects the collector names from existing files to populate `target.collectors`:
```sh
# collect the names of all available collectors
COLLECTORS=
for COLL_FILE in "$COLLECTORS_DIR"/*.collector.yaml; do
  [ -e "$COLL_FILE" ] || [ -L "$COLL_FILE" ] || continue
  COLLECTOR=$(sed -rn '/^collector_name: / s/collector_name: (.+)/'"'"'\1'"'"'/g p' "$COLL_FILE")
  if [ -z "$COLLECTORS" ]; then
    COLLECTORS=$COLLECTOR
  else
    COLLECTORS="$COLLECTORS, $COLLECTOR"
  fi
done
```
The above generates a `COLLECTORS` variable with names surrounded by quotes, ready to use in the YAML file.
As can be seen, having a native solution would be much appreciated to avoid these kind of workarounds.

**Additional context**

A bit of context: we are using the SQL exporter inside a Docker container, where we want to just provide new collector YAML configuration files without needing to update the main config file inside of the container every time.

**Comment by hhromic** [comment]
Looks like this can be easily accomplished using Go's built-in `Match()` function in `path/filepath`:
* https://pkg.go.dev/path/filepath#Match

If you are interested on this feature request, I could work on it and send a PR. Let me know!

**Comment by burningalchemist** [comment]
Hey @hhromic, thanks for the provided issues on enhancements and bugs. :+1:

For this particular ticket, it looks to be a valid use case, indeed. I appreciate any contributions as I'm pretty limited in time lately. So if you could provide a PR, we could look into it together and help it settle. 🙂

I'm always curious about how people use sql_exporter, organise their configuration files, etc. So many different views, ways of using. 😄

Thanks again! 👍

**Comment by hhromic** [comment]
Hi @burningalchemist , thanks for being open to contributions!
I will work out the implementation soon and send you a PR for reviewing 👍
