### ISSUE TITLE
New docker image release?

### ISSUE THREAD

**Issue by ricktaylor** [burningalchemist/sql_exporter#197]
Hi there,

Loving the exporter, it's just what we need, but we'd love to have the globbing syntax for collectors in the main yaml file feature, and I don't really want to start building my own images from scratch and lose upstream updates.

Any chance of new release soon, or have I failed to spot your release schedule?

Thanks for the great tool!

**Comment by burningalchemist** [comment]
Hi @ricktaylor, thanks a lot! 🙂

I usually create releases at the beginning of the month (we also receive some dependency updates to review/merge). Would the next week work for you, like March 1st?

**Comment by ricktaylor** [comment]
That would be amazing!  The timing couldn't be better, it coincides with our product release cycle :)

**Comment by burningalchemist** [comment]
Hey @ricktaylor, the new version is out: [0.10.0](https://hub.docker.com/r/burningalchemist/sql_exporter/tags) 🙂👍
