### ISSUE TITLE
Thundering herd prevention?

### ISSUE THREAD

**Issue by reubano** [burningalchemist/sql_exporter#205]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when sql_exporter taxes the DB by running all of its queries at once. It creates a [thundering herd](https://en.wikipedia.org/wiki/Thundering_herd_problem) that runs up the CPU usage.

**Describe the solution you'd like**

There should be a configurable jitter option that staggers the queries over time

**Describe alternatives you've considered**

I increased `min_interval` to `600s` but every 10 mins you see a huge spike in Azure SQL DTU%. 

**Additional context**

<img width="734" alt="Screen Shot 2023-03-09 at 10 02 43" src="https://user-images.githubusercontent.com/157864/224081931-dc4f7cb2-dc61-48c0-af1b-7fbb2fd90d45.png">

**Comment by burningalchemist** [comment]
Hey @reubano, given the design of this particular `sql_exporter` (it's synchronous, i.e. it's triggered by Prometheus requests), we want requested results as soon as possible. So I don't think we can introduce jitter. I did some research on that (branch `fix/thundering-hurd` [link](https://github.com/burningalchemist/sql_exporter/commit/df2d004fa0eec5ddbc4fc7cceea4c0f1d6c54afd)) by adding some random sleep between goroutine executions. Even though it works, it requires aligning with Prometheus request timeouts, local sql_exporter timeouts, etc. So, in my opinion, it doesn't seem to be a solution for the time being.

Instead, I think we can solve this problem differently by configuring multiple jobs (with specific intervals and other useful settings) from Prometheus. So you can group your queries in sql_exporter jobs and call them based upon your own schedule via query string. The prototype is ready, and I plan to release with the next `v0.14` version.

Related issue is here: #178
