### ISSUE TITLE
RPM installation issues

### ISSUE THREAD

**Issue by horfic** [burningalchemist/sql_exporter#242]
Hi,
i just installed the rpm on a centos 7 machine.

I found the following issues.

1. The -log.level parameter defined in the sql_exporter.service for the rpm packaging at the ExecStart got a type. It writes "-log-level" instead of "-log.level" which results in the application not beeing started
2. As the /etc/default/prometheus-sql-exporter environment file is missing after the install, the user and group for sql_exporter is also not getting created. Is this intended? 
3. Related to 2., the /etc/sql_exporter directory does not get created due to the missing env file which results that the sql_exporter.yml and the mssql_example.collector.yml is not getting copied

PS: Awesome application.

cheers,
Horfic

**Comment by burningalchemist** [comment]
Hi @horfic! Thanks for reporting the issue! I'll look into it, and fix accordingly. Sorry for the inconvenience. Thanks again and stay tuned. 🙂👍

**Comment by burningalchemist** [comment]
This should be fixed, the new package version will be available with the next release. 👍
