### ISSUE TITLE
ApplicationIntent=ReadOnly parameter support

### ISSUE THREAD

**Issue by mihaibudurescu** [burningalchemist/sql_exporter#252]
Hello,

can be supported passing parameters in the connection string, like for example ApplicationIntent=ReadOnly?
I see is documented and possible on go-mssqldb: https://github.com/microsoft/go-mssqldb

I have tried already but it's not working, this would be great in high availability environments.

Thank you,

**Comment by burningalchemist** [comment]
Hi @mihaibudurescu,

Parameters are supported for a long time. Could you provide some details for investigation?

One of the closed tickets has AAD authentication that's defined via the query string.
