### ISSUE TITLE
Select 1 - Exporter keeps running select 1 query to keep warehouse alive

### ISSUE THREAD

**Issue by AnserAli57** [burningalchemist/sql_exporter#27]
I have set the min_interval for 30m hopping that queries run in every 30 minutes but whenever Prometheus request exporter to scrape it won't run the queries due to min_interval instead its run select 1 query to keep the warehouse alive

**Comment by burningalchemist** [comment]
Hi @AnserAli57,

Could you please describe the desired behaviour from your perspective?

I'm trying to understand the issue, but so far I can tell, that we run `select 1` periodically as a ping to make sure the connection established is healthy.

We do not connect to the database each time - it would be resource-intensive. Instead, we have a connection pool of of open and idle connections that we need to keep alive.

Besides, could you also specify the driver or database you're trying to use?

**Comment by AnserAli57** [comment]
Hi
So my database is Snowflake
My desired behavior is that when prom request the exporter then exporter runs metrics with interval of 30 minutes . and between those interval  whenever prom request exporter to scrape ( by default 15 seconds ) it should just scrape already fetched metrics from the exporter while queries won't run until  min_interval and won't make any connection with my snowflake warehouse . as it won't give the warehouse any opportunity to sleep

**Comment by burningalchemist** [comment]
Hi @AnserAli57,

It looks like you want to disable the ping behaviour against SnowflakeDB. This is tricky as it doesn't align with the general behaviour of the application, where we want to keep the connection healthy and alive.

Without periodically pinging the database, we can't be sure that the connection is up to make a request when it's needed. This brings uncertainty and might break the application. Besides, usually there are also idle timeouts on the database side to automatically disconnect a client to keep less connections open. I'm not familiar with SnowflakeDB enough to know details, but it's a typical scenario.

Introducing a ping interval might be an option, but it needs to be thoroughly investigated as it might introduce unexpected behaviour. So it might take some time.

In your current situation I'd try something different:
- pick any Snowflake driver(be it in Go, Python or Javascript);
- create a simple request script, run it as a cron job, which would connect to your SnowflakeDB instance, run a query and exit. You can even pick one of the examples from Snowflake repository and slightly adjust it. Without cron job you can run it as a server as well to connect to the database every 30 mins, make a request, disconnect;
- spin up [Prometheus Push Gateway](https://github.com/prometheus/pushgateway) instance and push the result of your query to the Push Gateway (as a part of the script);
- Then you can scrape Prometheus Push Gateway instance with a regular Prometheus way.

This solution would keep a warehouse sleep between the queries, and it's easy to integrate into Prometheus environment.

**Comment by mapshen** [comment]
@burningalchemist pardon me for jumping in. In our use case, we don't need to check the connections to Snowflake that frequently, as each check will cost us money. 

Introducing a poll interval option would really help. In fact, that's how many other exporters approach it. On top of it, these exporters would often expose a metric on the upness of the upstream service based on the interval configured. Speaking of which, if users care about the health of database server, they could even configure a collector for that purpose at the moment, and we don't have to enforce it?

**Comment by burningalchemist** [comment]
Hi @mapshen! Yeah, I've checked the docs of Snowflake over the weekend to figure out the details of pricing. It's a tricky one. Anyways, I'll try to take a look into it. It might take some time, that's why the solution I offered above seems to help with mitigating the issue at the moment.

**Comment by burningalchemist** [comment]
Hi @mapshen @AnserAli57, I was able to reproduce the issue you're having with `SELECT 1`, prepared a quick solution. I'm currently looking into a better one. I'll keep you posted. 👍

**Comment by burningalchemist** [comment]
@mapshen @AnserAli57 Current solution is to add the new flag in the arguments:
```
./sql_exporter -config.enable-ping=false
```
I've tested it with SnowflakeDB instance and can confirm that we don't have any unnecessary `SELECT 1` queries. I'm going to prepare a new release shortly. Let me know if you have any further issues. I'm unable to extensively test it against SnowflakeDB, so your feedback is appreciated. 👍

**Comment by burningalchemist** [comment]
Hey @mapshen @AnserAli57, I'd like to know if you had a chance to try a new version already? Would be really cool to get your feedback. 👍

**Comment by mapshen** [comment]
Hey @burningalchemist, thanks so much for the fix! @AnserAli57 is testing it and will report back.

**Comment by AnserAli57** [comment]
Hey @burningalchemist Thanks a lot for the Fix it worked . we are not getting any Ping from exporter with select 1

**Comment by burningalchemist** [comment]
@AnserAli57 Cool, glad it worked for you! 👍 Please keep watching for the connectivity issues. As I mentioned before, I assume the connection to be reestablished in case of a bad one, but nothing is perfect. 😃
