### ISSUE TITLE
Display query duration in logs

### ISSUE THREAD

**Issue by reubano** [burningalchemist/sql_exporter#303]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I'm not able to figure out how long it took a job to run its queries.

**Describe the solution you'd like**

I want to be able to see the total query duration in the logs so that I can know what value to set `scrape_timeout`.

**Describe alternatives you've considered**

When I get a timeout error, I have to use trial and error to figure out the maximum number of queries I can run without timing out.

**Comment by burningalchemist** [comment]
Hey @reubano, currently there's already `scrape_duration_seconds` metric, which is exposed when you use `jobs`. It's not exposed for a single target mode, indeed.

I've prepared a small adjustment, so if the target name is provided in the config (this field is unavailable for now), you get the above and also `up` metrics. For unnamed single targets we preserve current operations for now to avoid any surprises for users.
