### ISSUE TITLE
Return results even if some query fails

### ISSUE THREAD

**Issue by Maros112358** [burningalchemist/sql_exporter#328]
**Is your feature request related to a problem? Please describe.**
In sql_exporter `0.12.1`, when using multiple targets and jobs, if one of the requests failed when scraping `/metrics`, other metrics were returned successfully. In sql_exporter `0.12.2`, if one query fails, whole request returns `500: Internal server error`.

**Describe the solution you'd like**
I prefered the behaviour in `0.12.1`. Since this was probably changed intentionally in the last release, I would like the option to return succesfully queried metrics, even if some of them fail.

**Describe alternatives you've considered**
Using `0.12.1`, but I need some bug fixes introduced in `0.12.2`. I also removed queries usually returning errors, but this is not good long term solution for me.

**Additional context**
I am monitoring multiple databases, and sometimes some queries fail, affecting data from other databses. I would like to avoid this.

**Comment by burningalchemist** [comment]
Fair enough, we should be able to watch error_scrape metric instead, which will be delivered soon. 👍

**Comment by Maros112358** [comment]
Tried out. Looks good to me. Thank you 👍
