### ISSUE TITLE
The problem of specifying a schema when capturing PostgreSQL metrics

### ISSUE THREAD

**Issue by gangzi59185** [burningalchemist/sql_exporter#346]
When I was capturing metrics in PostgreSQL, the data_ Source_ Name doesn't know how to configure a specific schema. When connecting to PostgreSQL normally, the parameter after the driver is, but it doesn't work here

**Comment by burningalchemist** [comment]
Hi @gangzi59185, I need more context to help you. Please share your DSN with redacted sensitive data. 👍

**Comment by gangzi59185** [comment]
<img width="1327" alt="image" src="https://github.com/burningalchemist/sql_exporter/assets/58457006/feee8d60-f98d-4e98-97c9-d7de1c5432a5">
The above are the parameters I connected to, because PostgreSQL has the concept of scheme, which defaults to pubic. However, my scheme is datago, and I don't know how to configure DSN to read data from datago's scheme

**Comment by gangzi59185** [comment]
<img width="1166" alt="image" src="https://github.com/burningalchemist/sql_exporter/assets/58457006/f3eef72b-bc74-400b-b067-a23a65fa1bb1">
The above are the parameters I connected to, because PostgreSQL has the concept of scheme, which defaults to pubic. However, my scheme is datago, and I don't know how to configure DSN to read data from datago's scheme

**Comment by burningalchemist** [comment]
Hey @gangzi59185, I guess the problem is that you're using special characters (`@`) in your password, so the entire string contains 2 `@` making DSN impossible to parse.

In the README.md we have the following part:

```
If your DSN contains special characters in any part of your connection string (including passwords), you might need to apply URL encoding (percent-encoding) to them. For example, p@$$w0rd#abc then becomes p%40%24%24w0rd%23abc.
```

So in your case the password `Datago@2021` should become `Datago%402021`. Please, give it a shot and let me know.

P.S. I was referring to the URL scheme name (`postgres://`) and not the database schema. It looks correct to me. 👍

**Comment by gangzi59185** [comment]
data_source_name: 'postgres://datago:xxxx@xxx:8000/mdmc_db?sslmode=disable&search_path=datago_db'
Thank you for your reply. I have fixed the password issue, but my problem is not a password issue. It is about the specified scheme in PostgreSQL. I have resolved it and added the parameter search_ Path=datago_ DB to specify a certain scheme, successfully read scheme=datago_ Data of db

**Comment by gangzi59185** [comment]
Haha, you're right. Thank you for your suggestion
