### ISSUE TITLE
`up`  metric to show that database connection was successful

### ISSUE THREAD

**Issue by fsiler** [burningalchemist/sql_exporter#366]
**Is your feature request related to a problem? Please describe.**
Right now, the `/metrics` endpoint returns all available data if the connection to the database is successful.  However, it would be really useful to have an `up` or `scrape_successsful` or `db_connection_successful` metric which shows that:
1. A database connection has been configured, and
2. by its value indicates whether or not a connection was successful (1) or unsuccessful (0).

I've also had occasion to notice when, for example with connecting with an unprivileged account, that an incomplete set of metrics was returned.  I would therefore also propose reflecting a metric (perhaps `sql_all_metrics_succeeded`) on `/metrics` which would, for example, have the value 1 when all requested queries are exposed and 0 otherwise, so that a user might have a cue to look in the logs for details.

**Describe the solution you'd like**
Metrics:
- `sql_exporter_connection_successful`
  - 1 on success
  - 0 on failure
  - labeled with name or index of configuration, something so you can tell where it's configured
- `sql_exporter_queries_successful`
  - 1 on everything worked
  - 0 on something failed
  -  labeled with name or index of configuration, something so you can tell where it's configured
- (optional, "would be nice") `sql_exporter_queries_bucket`
  - label `configured`: number of configured queries
  - label `successful`: number of successfully run queries
  - label `failed`: number of failed queries
  - labeled with name or index of configuration, something so you can tell where it's configured

**Describe alternatives you've considered**
Right now I'm having to write ugly `absent()` queries and do other detective work to figure out the former condition, and I haven't the faintest idea how to systematically work the second issue.

**Additional context**
n/a

**Comment by burningalchemist** [comment]
Hi @fsiler, this feature is already available for named targets. If you use a single connection mode (with `target` configuration block), you need to add `name` field, then you'll get `up` and `scrape_duration` metrics.

**Comment by fsiler** [comment]
This works great, many thanks!

**Comment by fsiler** [comment]
Sorry to bother- was hoping to get a new release with the `scrape_errors_total` metric included?  Wasn't sure if there's a regular release interval.

**Comment by burningalchemist** [comment]
Hi @fsiler, there's no regular release schedule, but I try to release at least every quarter. `v0.13` with this feature is hopefully coming this week. 🙂

**Comment by burningalchemist** [comment]
Hey @fsiler, `v0.13` release is available. 👍
