### ISSUE TITLE
parameter to set log file location

### ISSUE THREAD

**Issue by fsiler** [burningalchemist/sql_exporter#367]
**Is your feature request related to a problem? Please describe.**
I'm trying to run as a Windows service and I can't find events in the Log Viewer or the log file.

**Describe the solution you'd like**
Parameters, ideally both in the config file and command line, to set log file path.

**Describe alternatives you've considered**
Looked in Event Viewer and on disk, can't find log file.

**Comment by burningalchemist** [comment]
Hey @fsiler, `sql_exporter` is writing logs to `stdout` (or `stderr`) (or in the case of Windows `STD_OUTPUT_HANDLE` or `STD_ERROR_HANDLE`). There are no plans to involve `sql_exporter` in any filesystem activities like writing log files, managing log file rotation and so on. This is typically the job of the platform the service runs on to handle and route such data.

Writing logs to the Windows Event log requires direct interaction with this subsystem as well, which is also undesired.

Current workaround to keep things in the file would be to use `>` or `>>` redirects in your service definition string like [here](https://stackoverflow.com/questions/62250716/windows-redirect-stderr-and-stdout-to-same-program-when-piping/62268165#62268165). This also implies the user is responsible for log rotation, making sure there's enough disk space. etc. So overall there's an established process defined by the user.

There might be better alternatives for passing stdout stream to files in Windows, but unfortunately I don't have enough domain knowledge to suggest anything at this time.

**Comment by fsiler** [comment]
I appreciate the desire to not be involved in handling files.  However, the link you sent me just flat out doesn't work.  I have tried several variations and can't get this to work.  I'm wondering if I need to wrap in powershell or something to get this to function.  If I get it to work, would you accept a pull request showing the working method?

**Comment by burningalchemist** [comment]
Hey @fsiler, I'm sorry it didn't work. I need to find a Windows box somewhere to try things out myself. I also agree that you might need to use Powershell (e.g. `Tee-Object` method or something). Let me have a look and I come back to you.

As for the contribution, I'd be interested in the prior discussion first, any recipe that solves the problem without writing files from the service is appreciated.

I might return to this problem later as I already have the roadmap defined.

**Comment by fsiler** [comment]
I think it's probably possible to use a [Powershell wrapper as described here](https://learn.microsoft.com/en-us/archive/msdn-magazine/2016/may/windows-powershell-writing-windows-services-in-powershell) to just capture STDOUT and STDERR, so if I can get that to work I'll do a writeup and contribute a PR against the README :).

**Comment by burningalchemist** [comment]
Yeah, that'd be fantastic. If not, I think it's still essential for Windows users to have some insights on what's going on with the app, so I'll try to find a way to do this.

**Comment by burningalchemist** [comment]
Hey @fsiler, I think just a quick guide should be enough for starters. Feel free to open a PR and we'll discuss the details, I'm happy to assist as well. 👍

**Comment by burningalchemist** [comment]
It looks like the issue has been resolved. We can use `NSSM` to configure and manage the service in Windows, so I'll close this ticket for now.

Writing logs directly to the file or EventLog in Windows might be considered after the planned log library change.

**Comment by carrots66** [comment]
hello @fsiler did you ever get that guide or powershell script to set up logging in Windows? it would be very handy.
Thanks
