### ISSUE TITLE
Ignore no rows returned

### ISSUE THREAD

**Issue by JustNZ** [burningalchemist/sql_exporter#400]
Hey,

after now running the sql_exporter for a couple of weeks I have only one thing in mind that I would like to be added. Or maybe not because it's a stupid idea (don't know yet)

**Is your feature request related to a problem? Please describe.**
So my problem is I have a query which returns data based on a where condition which looks into the last 5 minutes. Since I only check for the last 5 minutes it can be that there are no rows and so the sql_exporter returns an error.

`Missing values for the requested columns: ...`

**Describe the solution you'd like**
I would really like to have a variable like `ignore_no_rows` which I can add to a metric - this then simply ignores when no rows are returned

**Describe alternatives you've considered**
-

**Additional context**
I'm using to goora/v2 module - so not sure if my request can be actually implemented within this exporter

**Comment by burningalchemist** [comment]
Hey @JustNZ, thanks for your suggestion. :+1:

I'd say, one option you might try (if you haven't already) is to add `name` to your target configuration. This also adds two more metrics (`scrape_errors_total` and `scrape_duration`). In this case, if your requested metric is unavailable, you'll still get the 200 response from sql_exporter with these metrics populated. To scrape them or not is up to you. The unavailable metric should have the last scraped value. In the logs, you'll still have the error message logged (missing values), which is fine and can be ignored.

Give it a shot, and let me know! 👍

**Comment by JustNZ** [comment]
Hey @burningalchemist ,
thanks for the suggestion and input.
Indeed I already have this label set and it also works the way you described.

My Goal with this feature request was only to get rid of those many log entrys since it is a bit confusing for other team members and I always have to tell them - that is fine ignore it :D

**Comment by burningalchemist** [comment]
Hey @JustNZ, yeah, got it! I'll think about it. 👍 I also have a plan to change the logging library, this might give us an option to put this message under `warning` log level and let users configure what they want to see.

**Comment by JustNZ** [comment]
perfect thanks a lot 👍

**Comment by burningalchemist** [comment]
Hey @JustNZ, so there's the flag `--config.ignore-missing-values`, which should help in your case. It's been merged to `master`, but not released yet. If you can try it out before (have to build, though), that'd be great. Otherwise, I'll release `v0.13.2` after holidays. 👍

**Comment by JustNZ** [comment]
Hey @burningalchemist ,
thanks a lot for this change. I was now able to test it and it looks very good 👍
