### ISSUE TITLE
Better handling of NULL return values in certain cases

### ISSUE THREAD

**Issue by keithf4** [burningalchemist/sql_exporter#407]
**Describe the bug**
Seeing the following error in syslog when columns are returning null values in PostgreSQL
```
Dec  6 17:34:04 cd-dc1-pg1 sql_exporter[147786]: ts=2023-12-06T22:34:04.944Z caller=klog.go:124 level=error func=Errorf msg="Error gathering metrics: [from Gatherer #1] [job=per_db_targets,target=alpha,collector=crunchy_per_db,query=ccp_stat_user_tables] sql: Scan error on column index 5, name \"idx_scan\": converting NULL to float64 is unsupported"
```

**To Reproduce**

Collector file: https://github.com/keithf4/pgmonitor/blob/sql_exporter/sql_exporter/common/crunchy_per_db_collector.yml

Underlying matview that collector query users: https://github.com/keithf4/pgmonitor/blob/sql_exporter/pgmonitor_extension/sql/matviews/matviews.sql#L4C1-L6C1

**Expected behavior**
Either don't return the metric, which is usually what I've seen in other cases, or return 0

**Configuration**

**Additional context**

**Comment by burningalchemist** [comment]
Hey @keithf4, thanks for reporting the issue, I'll have a look.

I guess for now it can be addressed with some SQL as a mitigation. 🙂👍

**Comment by keithf4** [comment]
Yeah I thought about that as well, but then realized I'd have to do A LOT of case statements to handle all the possible columns that could be NULLs.

**Comment by burningalchemist** [comment]
Hey @keithf4, the fix is merged to master. Give it a try if you have time, I plan to do a Christmas edition release. 😃👍

**Comment by keithf4** [comment]
Don't have a means of building at the moment, but we'll test the new binary as soon as it's out. Thank you!

**Comment by qfritz** [comment]
Thank you for the fix, it works on my side and resolve the same issue that I had. 🙏

**Comment by burningalchemist** [comment]
@qfritz Perfect! Thanks a lot for your feedback! 👏 Merry Christmas! 😃🎄
