### ISSUE TITLE
Clickhouse requests dosn't work after upgrade clickhouse driver to v2

### ISSUE THREAD

**Issue by deemon87** [burningalchemist/sql_exporter#544]
Hi,
after this commit [https://github.com/burningalchemist/sql_exporter/pull/466](url) dosn't work Clickhouse requests

```
[clickhouse][conn=1][127.0.0.1:9000][ping] <- pong

[clickhouse][conn=1][127.0.0.1:9000][ping] -> ping

sql_exporter[3905055]: ts=2024-06-18T13:16:03.530Z caller=klog.go:134 level=error func=Errorf msg="Error gathering metrics: [from Gatherer #1]

[job=clickhouse_common,target=clickhouse,collector=clickhouse_common,query=replication_queue_num_tries] invalid query"

sql_exporter[3905055]: [clickhouse-std][conn=0][127.0.0.1:9000] PrepareContext error: invalid query

**Comment by burningalchemist** [comment]
Hi @deemon87, what's the version of sql_exporter you're using? The driver has been updated to the v2 sometime ago. Also, make sure you're not using prepared context - Clickhouse doesn't support it. Check this discussion - https://github.com/burningalchemist/sql_exporter/discussions/542.

Let me know if it didn't help.

**Comment by burningalchemist** [comment]
Besides, I recommend switching to https://github.com/burningalchemist/sql_exporter/releases/tag/0.14.1 at least (check the release notes).
