### ISSUE TITLE
Config interpolation (secrets)

### ISSUE THREAD

**Issue by netikras** [burningalchemist/sql_exporter#565]
**Is your feature request related to a problem? Please describe.**
Am I the only one raising tickets for this project? :) IMO this exporter is severely underrated, I find it superior to other SQL exporters out there, mostly because of the flexibility of this exporter's configuration

Anyway, since I'm relying on it, I'm finding places that could be improved.

Would it be possible to implement interpolated configuration? My biggest concern is secrets, perhaps the whole DB URL.
It doesn't make much sense to shove the whole configuration into a k8s secret, as.. you know.. 99% of it is not _secret_ :) It's just a bunch of SQL queries that should live in a configmap

**Describe the solution you'd like**
I like what Grafana does with its grafana.ini: since it can contain secrets (e.g. smtp password), grafana discourages hardcoding them plain-text in a config. Instead, they encourage to use [interpolated configuration](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#env-provider), e.g.
user = alert@example.com
password = $__file{/etc/secrets/gf_smtp_password} ## or $__env{SMTP_PASSWORD}

Would it be possible to implement smth like this in sql_exporter? I imagine it shouldn't be terribly difficult, knowing that the connection strings must be urlencoded, so a non-urlencoded `$__file{/etc/sql_exporter/comemrce_db_credentials}` or `$__env{COMMERCE_DB_CREDS}` would stand out

Of course, this means making respective changes in the helm chart, to allow for custom env variables and volumes/mounts in the exporter's pod

I see the following as a viable usage example:
```
mysql://$__env{DB_USER}:$__file{/etc/secret/db_password}@db.example.com/$__env{DB_NAME}
```
or the whole thing
```
$__env{DB_CONN_STRING}
```

**Describe alternatives you've considered**
it's not like there are any :) 

**Additional context**
I'm VERY much happy about this project. When setting up monitoring, blackbox-exporter and birningalchemist/sql_exporter are my must-haves. As a devops / performance engineer I couldn't do my job well w/o them

**Comment by burningalchemist** [comment]
Hey @netikras, thanks for your suggestion and kind feedback. 😊 I believe this feature is already implemented (as per #427). Give it a try and let me know if it doesn't work?

**Comment by netikras** [comment]
@burningalchemist 
Thanks for the ref.! 

I must've missed a mention of this in the docs (readme, ./documentation/*). Is this feature explained anywhere? So do I just ${DB_PASSWORD} and it'll just work? Can I do this for the whole conn_string, i.e. load it all from the env_var?

**Comment by burningalchemist** [comment]
Yeah, exactly. You can interpolate a part of the DSN (as in password). If the env is set, it will be expanded, otherwise it will be left untouched (for easier debugging).

I have a plan for the documentation overhaul (a small static website with tips and recipes), but still struggle finding time to improve it so far. 😅

**Comment by netikras** [comment]
Thanks, that helps!

Just for the sake of completeness, I can interpolate a **part** of DSN, but I can't shove the whole DSN in an env var and just plop it in the sql_exporter.yml (i.e. it won't interpolate if the **whole** DSN is in the variable), right?

**Comment by burningalchemist** [comment]
The whole DSN also works. Out of the box, you can just use a predefined  `SQLEXPORTER_TARGET_DSN` environment variable that should populate the DSN string. But you can also use different combinations with the env interpolation - with the whole DSN string or parts of it like the password. The only requirement is it should resolve to the value.
