### ISSUE TITLE
Can't use UNIX socket for postgres connection

### ISSUE THREAD

**Issue by caseyandgina** [burningalchemist/sql_exporter#566]
Trying:  `data_source_name: 'postgres://app_sql_exporter@%2Frun%2Fpostgresql:5432/postgres'`

```
ts=2024-07-26T18:03:45.624Z caller=klog.go:134 level=error func=Errorf msg="Error gathering metrics: [from Gatherer #1] invalid URL escape \"%2F\""
ts=2024-07-26T18:03:45.624Z caller=klog.go:134 level=error func=Errorf msg="No metrics gathered: [from Gatherer #1] invalid URL escape \"%2F\""
```

**Comment by burningalchemist** [comment]
Hi @caseyandgina,

There's no need to encode the DSN as it needs to be parsed by dburl library.

We only might need to encode the password if it contains special characters.

**Comment by burningalchemist** [comment]
As mentioned above, this project historically relies on DSN and lately 'dburl' (https://github.com/xo/dburl) parsing library to handle connection strings for different databases, protocols, transports and parameters. It provides a unified way to connect to all the supported databases with minimal effort, and seems sufficient for the project goals. Please have a look at the dependency by the posted link for more details on parsing the strings. 👍

What's also possible is you may use environment variables as placeholders in the DSN string and interpolate parts of it as needed.

For now there is no intention to change the connection configuration anytime soon.

**Comment by jtougas** [comment]
`postgresql://${USER}@${SOCKET_FILE}/@{DATABASE}?${KEY}=${VALUE}`

So for user `postgres@foo`:

`postgresql://postgres@/var/run/postgresql/foo?sslmode=disable`
