### ISSUE TITLE
Include Oracle Autonomous Database driver

### ISSUE THREAD

**Issue by Maros112358** [burningalchemist/sql_exporter#576]
**Is your feature request related to a problem? Please describe.**
We would like to use sql_exporter with Oracle Autonomous Database. According to the article [Connecting a Go application to Oracle Database](https://blogs.oracle.com/developers/post/connecting-a-go-application-to-oracle-database), the only thing required should be to add package [go_ora](https://github.com/sijms/go-ora) to sql_exporter.

**Describe the solution you'd like**
Add [go_ora](https://github.com/sijms/go-ora) to sql_exporter.

**Describe alternatives you've considered**
Compile the sql_exporter with [go_ora](https://github.com/sijms/go-ora) ourselves.

**Comment by burningalchemist** [comment]
Hi @Maros112358, we have a PR for that (#575). I'm still evaluating the necessity to include it by default as it would increase the size of the binary.

Besides, I consider removing drivers for proprietary databases from the default build, and just leave MySQL and PostgreSQL. But it's not decided yet. If the database can be at least installed locally, then it'd be fine. With MSSQL you can install Express edition which is free. With Oracle I don't know if it's possible, but I haven't looked into it.

Currently, you can just add the driver, and rebuild the software, and it will work just fine.

**Comment by Maros112358** [comment]
Hello @burningalchemist, thank You for thorough elaboration.

Oracle Autonomous Database is available for free as a public docker image:
```
docker pull container-registry.oracle.com/database/adb-free:latest
```
Oracle Database is also available publicly https://www.oracle.com/database/free/get-started

We will rebuild the image for now, thank You.

**Comment by burningalchemist** [comment]
Hey @Maros112358, thanks for links. I'll have a look and try it out. If the size increase is small enough, I might add it then. 👍

I'll close the issue as it's already described in the linked PR. 😉
