### ISSUE TITLE
github-page for the Helm Chart is not working anymore - 404 error

### ISSUE THREAD

**Issue by tcraxs** [burningalchemist/sql_exporter#592]
Hi,

for some reasons the github page for the helm chart is not working anymore. I get a 404 error on https://burningalchemist.github.io/sql_exporter/

I do not know what changed or what is the problem, as the deployment of the github page was successful 2 month ago.

Can you have look?

Thanks and cheers,
Tobi

**Comment by burningalchemist** [comment]
Hi Tobi,

The page was never working as there is no `index.html` file available ([link](https://github.com/burningalchemist/sql_exporter/tree/gh-pages)).

Helm should work fine, though, as it relies on `index.yaml` which is present.

Could you share the error log from helm if you have any?
---

I'm working on publishing a documentation web page, so eventually there will be some static info available.

**Comment by tcraxs** [comment]
Okay sorry, forget it ... Its fully working, I had a mistake on my side.
