### ISSUE TITLE
Help shows incorrect syntax

### ISSUE THREAD

**Issue by MrCaffeen** [burningalchemist/sql_exporter#595]
**Describe the bug**
Script shows single dash in application help --help but app requires double dash

**To Reproduce**
run executable from command line, help options show single dash

**Expected behavior**
Should display double dash as expected & Required

**Comment by burningalchemist** [comment]
Hi @MrCaffeen, this behaviour is defined by the standard Golang's library `flag` ([link](https://pkg.go.dev/flag#hdr-Command_line_flag_syntax)), that's used in the project, and is not something I may change. 

```
...The following forms are permitted:

-flag
--flag   // double dashes are also permitted
-flag=x
-flag x  // non-boolean flags only
One or two dashes may be used; they are equivalent...
```

If for some reason single dash doesn't work on your machine, just use double dash. 👍
