### ISSUE TITLE
ClickHouse driver does not work as expected

### ISSUE THREAD

**Issue by nuclon** [burningalchemist/sql_exporter#628]
With version 0.16.0, when the connection to clickhouse is used, all queries fail with following error:

`nc=Errorf msg="Error gathering metrics: [from Gatherer #1] [collector=data_check,query=test] invalid INSERT query: select 1 AS test"`

Not sure, why it says "invalid INSERT query", but it seems the problem is somewhere there :)

**Comment by burningalchemist** [comment]
Hi @nuclon, could you please share your configuration (redacted)?

**Comment by burningalchemist** [comment]
I'll convert it to discussion at the moment, you may also find related Clickhouse discussions [here](https://github.com/burningalchemist/sql_exporter/discussions?discussions_q=clickhouse+is%3Aclosed).
