### ISSUE TITLE
Debian package for sql_exporter

### ISSUE THREAD

**Issue by kampagnol** [burningalchemist/sql_exporter#93]
**Is your feature request related to a problem? Please describe.**
I woud like a properly packaged binary for deployment on debian (and possibly other debian-based systemd systems).

**Describe the solution you'd like**
A downloadable .DEB, or (better still) inclusion in the regular debian repositories.

**Describe alternatives you've considered**
It is possible to deploy using the release TAR, but the point is to have a native DEB for easy installation.

**Additional context**
I have done some preliminary work, and managed to create a .DEB package that seems to install correctly. However, I am not an expert on the matter, and I am quite sure that it is possible to improve.

Is this something you would consider? If yes, what would be the next steps?

Regards, Kevin

**Comment by burningalchemist** [comment]
@kampagnol 

Hi Kevin,

Yeah, I'd say if there is demand, why not. I'm happy to add deb packages as well. Feel free to share if you already have something. I'll take a look. :+1:

I can create a deb package as another artifact that can be downloaded from the Github release page. Would this work for you? I don't think I have the resources to maintain a separate deb repository for one application.

I think it's also possible to submit it to some of the Debian repositories. I might need time to investigate it and would appreciate some help here.

Let me know what you think.

Kind regards,
Sergei

**Comment by kampagnol** [comment]
Artifact in the same repository seems just fine to me.

Currently there is a "prometheus-sql-exporter" in the debian repository - I am assuming there are functional differences there; do you have any pointers on the what the differences may be? This might play a part in the "naming" of the deb package.

**Comment by kampagnol** [comment]
I am attaching a tar.gz of what I've done so far

[prometheus-mssql-exporter-0.8.6.tar.gz](https://github.com/burningalchemist/sql_exporter/files/8473374/prometheus-mssql-exporter-0.8.6.tar.gz)

Salient points:

- I named the package "prometheus-mssql-exporter" - but of course that's just me; the package file contents and/or names would have to be adjusted for whatever name you use
- ./debian/changelog would need to be built from your pipeline, I suppose
- ./debian/compat set to debhelper version 10 - it worked for me, I don't know really what this implies
- ./debian/control would need to be built from your pipeline, and the Maintainer replaced with your details
- ./debian/prometheus-mssql-exporter.install lists the files that the DEB would need to deploy and their locations; I have opted to have the collector files to reside in /etc/prometheus/prometheus-mssql-exporter.conf.d, and to have the main config file to reside in /etc/prometheus
- ./debian/prometheus-mssql-exporter.postinst creates a user "prometheus-mssql-exporter" user for the service to run as, with home folder /var/lib/prometheus-mssql-exporter (I used other exporters such as node and blackbox to borrow this idea)
- ./debian/prometheus-mssql-exporter.service is the sevice unit file for systemd
- ./debian/rules is the minimum implementation
- ./debian/source/format is the minumim requirement
- ./etc contents is self-explanatory
- ./usr contents is self-explanatory (obviously I renamed the binary)

After I unpack the tar, I cd into the new "prometheus-mssql-exporter-0.8.6" folder and run "dh binary-arch"

When installing, I get a warning "repository is broken <package> has no size information" - I have not figured out how to get rid of this warning, but it works anyhow

Anything else you need from me about this?

Regards, Kevin

**Comment by kampagnol** [comment]
...and even though I don't have much free time, yes I would assist with the task of submitting to debian repositories. But I suppose one would need to iron out some things first.

Regards, Kevin

**Comment by burningalchemist** [comment]
@kampagnol Thanks! I have also limited availability at the moment but I'll try to take a look soon and keep you posted. :+1:

**Comment by burningalchemist** [comment]
Hi @kampagnol! Just a quick update. I've taken a look at packaging `sql_exporter` as a package for linux distributions. It looks trivial, so I'll schedule some time and try to integrate it with the current release flow. The package should be available in the list of artifacts for future releases. Stay tuned. :)

As for adding it to the linux repositories, it might be a bit tricky. Some of the embedded drivers (e.g. mssql or snowflake) do not represent FLOSS in terms of licensing, and might be ignored by the community. I'm not familiar with the process, though.

Kind regards,
Sergei

**Comment by kampagnol** [comment]
Great news, I'll wait for more feedback!

Regards, Kevin.

**Comment by burningalchemist** [comment]
Hi @kampagnol, I'm sorry for the silence, there is a lot of stuff going on. 

I didn't forget about this issue, though. I've prepared the deb/rpm package provisioning process. I still need to test some OS-specific configuration parameters (e.g. systemd parameters, defaults, etc). But it should be available with the next release (v0.8.8).

**Comment by burningalchemist** [comment]
Deb/rpm packages should be available with the next release as downloadable artifacts.

**Comment by kampagnol** [comment]
That's great to hear, and many thanks. Looking forward to testing it as soon as it becomes available.
